### ISSUE TITLE
Data Writers didn't initialize properly

### ISSUE THREAD

**Issue by jameshughes7** [dubeyrupesh/Gatling-Kinesis#1]
Hi @dubeyrupesh 

Thanks first of all for this repo you've made. I'm looking to execute a performance test against our kinesis stream and I 
have been trying to make this repo work.
_Disclaimer: I am not a Scala developer so I am learning the ropes still when it comes to fully understanding the ins and outs of this repo._ 

I'm seeing an issue when running `gatling:testOnly PutRecordsInKinesisStream` using SBT.

**Some context:**

- I have configured the repo to point to my own kinesis stream with correct region.
- I have also updated `build.sbt` and `project/plugins.sbt` to what is in this repo's **Sam** branch.
- The format of the `src/test/resources/json/sample_event_1.json` has also been customised according to the kinesis stream request we require.
- sbt version: `0.13.15`
- sbt script version: `1.3.13`

Here's is the error I am seeing:

```
java.lang.Exception: DataWriters didn't initialize properly
[error] 	at io.gatling.core.stats.DataWritersStatsEngine$.io$gatling$core$stats$DataWritersStatsEngine$$$anonfun$6(StatsEngine.scala:99)
[error] 	at io.gatling.core.stats.DataWritersStatsEngine$lambda$$statsEngineFuture$2.apply(StatsEngine.scala:97)
[error] 	at io.gatling.core.stats.DataWritersStatsEngine$lambda$$statsEngineFuture$2.apply(StatsEngine.scala:97)
[error] 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
[error] 	at scala.util.Try$.apply(Try.scala:192)
[error] 	at scala.util.Success.map(Try.scala:237)
[error] 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
[error] 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[error] 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[error] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
[error] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
[error] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Simulation PutRecordsInKinesisStream failed.
[info] Simulation(s) execution ended.
[error] Failed tests:
[error] 	PutRecordsInKinesisStream
[error] (gatling:testOnly) sbt.TestsFailedException: Tests unsuccessful
```

**Attempt to update the gatling.conf file as a result of seeing error above:**

If I uncomment the line `# writers = "console, file" # The lists of DataWriters to which Gatling write simulation data (currently supported : "console", "file", "graphite", "jdbc")` so that writers = "console,file" is being used, I see the following error: 

```
[error] com.typesafe.config.ConfigException$WrongType: gatling.conf @ file:/home/jenkinsx/repos/Gatling-Kinesis/target/scala-2.11/test-classes/gatling.conf: 116: gatling.data.writers has type STRING rather than LIST
[error] 	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:159)
[error] 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
[error] 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
[error] 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
[error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
[error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
[error] 	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:252)
[error] 	at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:323)
[error] 	at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:381)
[error] 	at io.gatling.core.config.GatlingConfiguration$.mapToGatlingConfig(GatlingConfiguration.scala:212)
[error] 	at io.gatling.core.config.GatlingConfiguration$.load(GatlingConfiguration.scala:98)
[error] 	at io.gatling.app.Gatling$.start(Gatling.scala:55)
[error] 	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
[error] 	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
[error] 	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Simulation PutRecordsInKinesisStream failed.
[info] Simulation(s) execution ended.
[error] Failed tests:
[error] 	PutRecordsInKinesisStream
[error] (gatling:testOnly) sbt.TestsFailedException: Tests unsuccessful
```

**Any help making this work would be greatly appreciated** 👍

**Comment by dubeyrupesh** [comment]
@jameshughes7 : First of all apologies as I missed this message. I think it is happening because of the API versions.  I can help you with it, if it is still relevant to you.
